#=====================================================================
## Author: Crossan Cooper
## Last Modified: 06-08-2026

## file use: Run the code-only UA recruiting town-panel workflow from RStudio
## in the active Out-of-State Enrollment codebase. The central paper outputs
## are the PPML admissions-visit tables written to main_results.
#
## inputs:
## 1. data/full_ua_recruiting_scrape.csv -- admissions visit records
## 2. data/all_alabama_data.csv -- curated UA commencement analysis input
## 3. town_matching/data/raw_online -- cached NCES/ACS online files, if present
#
## outputs:
## 1. town_matching/output -- town links, denominators, panels, PPML tables,
##    supporting coefficient grids, diagnostics, and figures
#=====================================================================

#=====================================================================
# 0 - paths and RStudio options
#=====================================================================

rm(list = ls())

### i. run options

## (a) Edit these values before clicking Source in RStudio.
refresh_online <- FALSE
full_robustness <- TRUE
horizons <- "5,6"

### ii. source the shared path config

default_shared_path <- "/Users/crossancooper/Dropbox/Professional/active-projects/admissions_project_personal/Out-of-State-Enrollment/code/crossan/_shared/project_paths.R"
project_path_candidates <- c(
  file.path(getwd(), "project_paths.R"),
  file.path(getwd(), "_shared", "project_paths.R"),
  file.path(getwd(), "..", "_shared", "project_paths.R"),
  file.path(getwd(), "code", "crossan", "_shared", "project_paths.R"),
  default_shared_path
)
project_path_candidates <- project_path_candidates[file.exists(project_path_candidates)]
if (length(project_path_candidates) == 0) {
  stop("Could not find project_paths.R. Open the active repo in RStudio or update default_shared_path.")
}
source(project_path_candidates[[1]])

### iii. executable paths and output folders

python <- Sys.getenv("PYTHON", "python3")
rscript <- Sys.getenv("RSCRIPT", "Rscript")

town_code_dir <- pathTownMatchingCode
town_output_dir <- pathRecruitingOutput
raw_online_dir <- file.path(pathHome, "town_matching", "data", "raw_online")
robustness_dir <- file.path(town_output_dir, "robustness")
main_results_dir <- file.path(town_output_dir, "main_results")
dir.create(town_output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(raw_online_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(robustness_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(main_results_dir, recursive = TRUE, showWarnings = FALSE)

#=====================================================================
# 1 - helpers
#=====================================================================

### i. run one external command and stop on failure

run_step <- function(step_name, command, arguments) {
  cat(sprintf("\n[%s] %s\n", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), step_name))
  cat("  command:", paste(c(command, arguments), collapse = " "), "\n")
  status <- system2(command, arguments)
  if (!identical(status, 0L)) {
    stop(sprintf("Step failed: %s", step_name), call. = FALSE)
  }
}

#=====================================================================
# 2 - input and output paths
#=====================================================================

### i. locked inputs generated by the active legacy scripts

recruiting_path <- file.path(pathData, "full_ua_recruiting_scrape.csv")
student_path <- file.path(pathData, "all_alabama_data.csv")

### ii. town-matching outputs

match_path <- file.path(town_output_dir, "ua_recruiting_to_student_town_matches.csv")
denom_path <- file.path(town_output_dir, "ua_high_school_denominators_online_panel_matched.csv")
panel_t5_path <- file.path(town_output_dir, "ua_visit_t_graduates_t_plus_5_panel.csv")
panel_t6_path <- file.path(robustness_dir, "ua_visit_t_graduates_t_plus_6_panel.csv")
acs_path <- file.path(town_output_dir, "ua_acs_town_covariates_2017.csv")
town_fe_t5_coef_path <- file.path(robustness_dir, "ua_visit_t_graduates_t_plus_5_robustness_coefficients.csv")
town_fe_t6_coef_path <- file.path(robustness_dir, "ua_visit_t_graduates_t_plus_6_robustness_coefficients.csv")
no_town_fe_coef_path <- file.path(town_output_dir, "no_town_fe", "ua_visit_graduate_no_town_fe_coefficients.csv")

#=====================================================================
# 3 - build town links, denominators, panels, and controls
#=====================================================================

### i. link recruiting towns to commencement-origin towns

run_step("town_linkage", python, c(
  file.path(town_code_dir, "town_linkage.py"),
  "--recruiting-path", recruiting_path,
  "--student-path", student_path,
  "--output-dir", town_output_dir
))

### ii. build NCES high-school denominators keyed to the linked town universe

denominator_args <- c(
  file.path(town_code_dir, "build_high_school_denominators.py"),
  "--raw-dir", raw_online_dir,
  "--output", file.path(town_output_dir, "ua_high_school_denominators_online.csv"),
  "--panel-matched-output", denom_path,
  "--match-review", file.path(town_output_dir, "ua_high_school_denominators_online_match_review.csv"),
  "--summary", file.path(town_output_dir, "ua_high_school_denominators_online_summary.md")
)
if (refresh_online) {
  denominator_args <- c(denominator_args, "--force-download")
}
run_step("high_school_denominators", python, denominator_args)

### iii. build the preferred t+5 panel before ACS matching, because ACS uses the
###      panel town universe as its target.

run_step("visit_graduate_panel_t5", python, c(
  file.path(town_code_dir, "build_visit_graduate_panel.py"),
  "--recruiting-path", recruiting_path,
  "--student-path", student_path,
  "--match-path", match_path,
  "--denominator-path", denom_path,
  "--output", panel_t5_path,
  "--summary", file.path(town_output_dir, "ua_visit_t_graduates_t_plus_5_summary.md")
))

### iv. build ACS covariates after the t+5 panel establishes the target towns.

acs_args <- c(
  file.path(town_code_dir, "build_acs_town_covariates.py"),
  "--panel", panel_t5_path,
  "--raw-dir", raw_online_dir,
  "--output", acs_path,
  "--review", file.path(town_output_dir, "ua_acs_town_covariates_2017_match_review.csv"),
  "--summary", file.path(town_output_dir, "ua_acs_town_covariates_2017_summary.md")
)
if (refresh_online) {
  acs_args <- c(acs_args, "--force-download")
}
run_step("acs_town_covariates", python, acs_args)

### v. build the t+6 panel for the second paper horizon and horizon checks.

run_step("visit_graduate_panel_t6", python, c(
  file.path(town_code_dir, "build_visit_graduate_panel.py"),
  "--recruiting-path", recruiting_path,
  "--student-path", student_path,
  "--match-path", match_path,
  "--denominator-path", denom_path,
  "--horizon", "6",
  "--output", panel_t6_path,
  "--summary", file.path(robustness_dir, "ua_visit_t_graduates_t_plus_6_summary.md")
))

#=====================================================================
# 4 - main PPML results, supporting regressions, and figures
#=====================================================================

### i. town fixed-effect coefficient grids. PPML rows from these grids are
###    extracted below as the main paper estimates.

run_step("town_fe_grid_t5", rscript, c(
  file.path(town_code_dir, "run_visit_graduate_robustness.R"),
  "--horizon=5",
  paste0("--panel=", panel_t5_path),
  paste0("--output=", town_fe_t5_coef_path)
))

if (full_robustness) {
  run_step("town_fe_grid_t6", rscript, c(
    file.path(town_code_dir, "run_visit_graduate_robustness.R"),
    "--horizon=6",
    paste0("--panel=", panel_t6_path),
    paste0("--output=", town_fe_t6_coef_path)
  ))
}

run_step("no_town_fe", rscript, c(
  file.path(town_code_dir, "run_visit_graduate_no_town_fe.R"),
  paste0("--horizons=", horizons),
  paste0("--denominators=", denom_path),
  paste0("--acs=", acs_path)
))
run_step("ppml_main_results", rscript, c(
  file.path(town_code_dir, "build_recruiting_ppml_main_results.R"),
  paste0("--town-fe-t5=", town_fe_t5_coef_path),
  paste0("--town-fe-t6=", if (full_robustness) town_fe_t6_coef_path else ""),
  paste0("--no-town-fe=", no_town_fe_coef_path)
))
run_step("visit_drivers", rscript, file.path(town_code_dir, "run_recruiting_visit_driver_analysis.R"))
run_step("town_fe_diagnostics", rscript, file.path(town_code_dir, "run_town_fe_identification_diagnostics.R"))
run_step("town_trend_checks", rscript, c(
  file.path(town_code_dir, "run_visit_graduate_town_trend_checks.R"),
  paste0("--horizons=", horizons)
))
run_step("paper_coefficient_figures", rscript, file.path(town_code_dir, "plot_recruiting_paper_figures.R"))
run_step("visit_distribution_figures", rscript, file.path(town_code_dir, "plot_visit_count_distribution.R"))

cat("\nRecruiting town-panel workflow completed.\n")
cat("Output:", town_output_dir, "\n")
